# Generated by Django 6.0.4 on 2026-04-23 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('others', 'Others'), ('female', 'Female')], max_length=200)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='writers_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('Summary', models.TextField()),
                ('book_cover', models.ImageField(upload_to='book_covers/')),
                ('pub_year', models.PositiveBigIntegerField()),
                ('price', models.FloatField()),
                ('genre', models.CharField(max_length=150)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.writer')),
            ],
        ),
    ]
