# Generated by Django 6.0.3 on 2026-04-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newsandevent_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsandevent',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
